### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by sumeetkr13** [SethEBaldwin/fastpivot#2]
Running `pip install fastpivot` on Google Colab gives the following error (also received a similar error on local Mac M2):

```
Collecting fastpivot
  Using cached fastpivot-0.1.12.tar.gz (170 kB)
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
time: 22.7 s (started: 2023-12-21 05:01:57 +00:00)
```

**Comment by SethEBaldwin** [comment]
Unfortunately I'm not sure what is going on here. I'm able to successfully install fastpivot in a virtual environment on my own machine (running Ubuntu). I'm not sure I have time to look into this, but can you provide any more details? Is there a trace? What version of python and packages are you running (via pip freeze)?

**Comment by sumeetkr13** [comment]
The specifications of the virtual environment on my laptop are:

- Apple M2 Pro, Ventura 13.4
- 
[requirements.txt](https://github.com/SethEBaldwin/fastpivot/files/13745512/requirements.txt)
- Pyhton 3.10.10

Full error message below:

```
Collecting fastpivot
  Using cached fastpivot-0.1.12.tar.gz (170 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      /private/var/folders/5v/hlyp76wd72qfrlds5syt3pjw0000gn/T/pip-build-env-a285sc7o/overlay/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/5v/hlyp76wd72qfrlds5syt3pjw0000gn/T/pip-install-t3bs99q_/fastpivot_c38f40e135d8451aa148b1571ce4a197/fastpivot/pivot.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef int k
          cdef int idx
          cdef double value = 0.0
          cdef double med
          stdsort(vec.begin(), vec.end())
          idx = vec.size() / 2
                           ^
      ------------------------------------------------------------

      fastpivot/pivot.pyx:504:21: Cannot assign type 'double' to 'int'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          return med

      # very slow on duplicates
      cdef double median_cython(vector[double] &vec):
          cdef int k = 0
          cdef int mid = vec.size() / 2
                                    ^
      ------------------------------------------------------------

      fastpivot/pivot.pyx:516:30: Cannot assign type 'double' to 'int'
      Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
      Compiling fastpivot/pivot.pyx because it changed.
      [1/1] Cythonizing fastpivot/pivot.pyx
      Traceback (most recent call last):
        File "/Users/sumeetkumar/sk_python/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/sumeetkumar/sk_python/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/sumeetkumar/sk_python/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/5v/hlyp76wd72qfrlds5syt3pjw0000gn/T/pip-build-env-a285sc7o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/5v/hlyp76wd72qfrlds5syt3pjw0000gn/T/pip-build-env-a285sc7o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/5v/hlyp76wd72qfrlds5syt3pjw0000gn/T/pip-build-env-a285sc7o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
        File "/private/var/folders/5v/hlyp76wd72qfrlds5syt3pjw0000gn/T/pip-build-env-a285sc7o/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/5v/hlyp76wd72qfrlds5syt3pjw0000gn/T/pip-build-env-a285sc7o/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: fastpivot/pivot.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: There was an error checking the latest version of pip.
```

**Comment by SethEBaldwin** [comment]
Ah, thank you. I believe that was fixed in the latest PR but I haven't released the new version yet. Will try to do that when I have some time.

**Comment by SethEBaldwin** [comment]
Ok, I've rolled out a new version 0.1.13
Please let me know if this resolves the issue.

**Comment by sumeetkr13** [comment]
Yup works now. Thanks!
